// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"sort"

	"github.com/miekg/dns"

	"github.com/mallardduck/BrambleGate/plugins/querylog"
)

// DashboardActivityData is the Dashboard's Activity section (dev-docs/
// query-log.md's Phase 7d) — everything sourced from querylog.CurrentLog().
// Zero-value when Query Log is disabled; Dashboard only reads it when
// data.Settings.QueryLog.Enabled is true.
type DashboardActivityData struct {
	Totals querylog.Totals
	Series []querylog.Bucket
	// TopDomains/TopClients/StoreConfigured: TopDomains/TopClients are only
	// populated when Query Log's durable Store is on (Phase 7b) — the cheap
	// rollups above work regardless. StoreConfigured gates whether the
	// top-N cards show data or a "turn persistence on" note; it's one flag
	// rather than two since both queries share the same underlying
	// Store-configured check (Log.TopDomains/TopClients, log.go).
	TopDomains      []querylog.DomainCount
	TopClients      []querylog.ClientCount
	StoreConfigured bool
	// ClientActivity is the per-client stacked time series behind the
	// Client Activity chart — Store-backed like TopDomains/TopClients, so
	// only populated (and only rendered) when StoreConfigured.
	ClientActivity querylog.ClientActivitySeries
}

// DashboardExtraHead is the Dashboard page's extra <head> content (see
// ui.Base's extraHead parameter) — Chart.js plus this project's own
// lifecycle glue (static/js/charts.js), loaded only here rather than
// globally, since no other page uses charts.
func DashboardExtraHead() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script src=\"/static/js/chart.umd.min.js\"></script><script src=\"/static/js/charts.js\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// DashboardActivityTop is the Activity section's header + tiles — the
// primary target of the section's 60s poll (dev-docs/query-log.md: "slower
// poll than the live log, seconds-to-minutes, summary data not a live
// feed"), a full outerHTML self-replace same as Query Log's grid fragment
// (querylog.templ). Kept deliberately small (no VLAN breakdown/tables, no
// canvases) so it can sit directly above DashboardCharts on the page —
// DashboardActivityBottom carries the rest of the non-chart content, kept
// visually *below* the charts (the original layout) even though it isn't
// contiguous with this element once DashboardCharts sits between them; see
// DashboardActivityBottom's own doc comment for how it still stays live.
func DashboardActivityTop(data DashboardActivityData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div id=\"dashboard-activity\" class=\"mb-8\" hx-get=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(PathDashboardActivity)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard_stats.templ`, Line: 54, Col: 73}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" hx-trigger=\"every 60s\" hx-swap=\"outerHTML\"><h2 class=\"text-lg font-heading font-semibold mb-4 flex items-center\">Activity")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = helpTooltip("Traffic stats since this process started (not since install) — refreshed every 60s. Distinct from the Query Log page, which shows individual queries in near-real-time.").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</h2><div class=\"grid grid-cols-2 sm:grid-cols-4 gap-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = activityTile("Total queries", fmt.Sprintf("%d", data.Totals.Queries)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = activityTile("Cache hit rate", pctLabel(sourceGroupTotal(data.Totals.BySource, "cache", "vlancache"), data.Totals.Queries)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = activityTile("Answered locally", pctLabel(sourceGroupTotal(data.Totals.BySource, "localrecords", "mdnsbridge", "hosts"), data.Totals.Queries)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = activityTile("Forwarded upstream", pctLabel(sourceGroupTotal(data.Totals.BySource, "forward"), data.Totals.Queries)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// DashboardActivityBottom is the VLAN breakdown + Top domains/clients
// tables — visually below DashboardCharts (the original layout), but still
// driven by DashboardActivityTop's 60s poll: htmx's hx-swap-oob lets one
// poll response update two non-contiguous DOM locations, so
// dashboardActivityFragment (handlers_ui.go) returns
// DashboardActivityTop as the primary outerHTML target and this element,
// marked hx-swap-oob, gets swapped into its own spot below the charts.
// hx-swap-oob is a no-op on the static markup emitted for the initial page
// load (it only takes effect when htmx processes a request's response) —
// oob semantics only apply on the poll fragment.
func DashboardActivityBottom(data DashboardActivityData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div id=\"dashboard-activity-bottom\" class=\"mb-8\" hx-swap-oob=\"true\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = vlanBreakdown(data.Totals.ByVLAN, data.Totals.Queries).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"grid grid-cols-1 sm:grid-cols-2 gap-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = topDomainsCard(data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = topClientsCard(data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// DashboardActivity renders both halves of the Activity section back to
// back with no charts in between — used by dashboardActivityFragment
// (handlers_ui.go), the 60s poll endpoint, whose response needs to carry
// both the primary swap target (DashboardActivityTop) and the
// out-of-band-swapped remainder (DashboardActivityBottom) in one payload.
// The full page (ui.Dashboard) instead calls the two halves separately with
// DashboardCharts wedged between them, to get the original tiles -> charts
// -> VLAN/tables visual order.
func DashboardActivity(data DashboardActivityData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = DashboardActivityTop(data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = DashboardActivityBottom(data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// DashboardCharts is the Dashboard's chart canvases — rendered exactly once
// as part of the page/fragment that first shows the Activity section (never
// re-rendered by DashboardActivityTop's own 60s outerHTML poll, which would
// tear down and recreate every Chart.js instance). Each canvas is created
// empty by charts.js on load and kept alive for the page's lifetime; data
// arrives via #chart-poller's own JSON poll of /api/dashboard/charts
// (DashboardChartsPayload) and is applied in place with chart.update(),
// which is what gives Chart.js's animated transitions rather than a cold
// redraw. The "Cache activity" card is always shown once Query Log is on
// (no more data-driven appear/disappear per vlancache activity) — a fixed
// set of cards, like Pi-hole's dashboard, since a card that only sometimes
// exists has nowhere to live once canvases stop being recreated per poll.
func DashboardCharts(data DashboardActivityData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div id=\"dashboard-charts\"><div id=\"chart-poller\" hx-get=\"/api/dashboard/charts\" hx-trigger=\"load, every 60s\" hx-swap=\"none\"></div><div class=\"rounded border border-bramble-border bg-bramble-bg-card shadow-sm p-4 mb-4\"><h3 class=\"text-sm font-semibold mb-3\">Queries — last 24h</h3><div class=\"h-48 relative\"><canvas id=\"chart-series\" data-chart=\"timeseries\"></canvas></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = clientActivityCard(data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<div class=\"grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4\"><div class=\"rounded border border-bramble-border bg-bramble-bg-card shadow-sm p-4\"><h3 class=\"text-sm font-semibold mb-3\">Sources</h3><div class=\"h-48 relative\"><canvas id=\"chart-sources\" data-chart=\"doughnut\"></canvas></div></div><div class=\"rounded border border-bramble-border bg-bramble-bg-card shadow-sm p-4\"><h3 class=\"text-sm font-semibold mb-3\">Query types</h3><div class=\"h-48 relative\"><canvas id=\"chart-qtypes\" data-chart=\"doughnut\"></canvas></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = vlanCacheActivityCard().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// dashboardActivityDisabled is a slim CTA shown in place of the Activity
// section when Query Log is off — mirrors Query Log page's own disabled
// message (querylog.templ) rather than rendering an empty/broken section.
func dashboardActivityDisabled() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<div class=\"mb-8 rounded border border-bramble-border bg-bramble-bg-card shadow-sm p-4\"><h2 class=\"text-sm font-semibold mb-1\">Activity</h2><p class=\"text-bramble-muted text-sm\">Enable Query Log in <a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 templ.SafeURL
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(PathSettings))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard_stats.templ`, Line: 148, Col: 60}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\" class=\"text-bramble-primary hover:underline\">Settings</a> to see traffic stats here.</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func activityTile(label, value string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var9 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var9 == nil {
			templ_7745c5c3_Var9 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<div class=\"rounded border border-bramble-border bg-bramble-bg-card shadow-sm p-4\"><p class=\"text-xs text-bramble-primary uppercase tracking-wide\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(label)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard_stats.templ`, Line: 155, Col: 73}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</p><p class=\"text-2xl font-heading font-semibold mt-1 tabular-nums\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var11 string
		templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(value)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard_stats.templ`, Line: 156, Col: 74}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func vlanBreakdown(byVLAN map[string]int64, total int64) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var12 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var12 == nil {
			templ_7745c5c3_Var12 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if len(byVLAN) > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "<div class=\"rounded border border-bramble-border bg-bramble-bg-card shadow-sm p-4 mb-4\"><h3 class=\"text-sm font-semibold mb-3\">Queries by VLAN</h3><div class=\"flex flex-col gap-2\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, lc := range sortedCounts(byVLAN) {
				templ_7745c5c3_Err = vlanBar(lc, total).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

func vlanBar(lc labelCount, total int64) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var13 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var13 == nil {
			templ_7745c5c3_Var13 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "<div class=\"flex items-center gap-3 text-sm\"><span class=\"w-24 truncate shrink-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var14 string
		templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(vlanBarLabel(lc.Label))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard_stats.templ`, Line: 175, Col: 63}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</span><div class=\"flex-1 h-2 rounded bg-bramble-bg-input overflow-hidden\"><div class=\"h-full bg-bramble-primary\" style=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var15 string
		templ_7745c5c3_Var15, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(fmt.Sprintf("width:%.1f%%", barPct(lc.Count, total)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard_stats.templ`, Line: 177, Col: 102}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "\"></div></div><span class=\"w-10 text-right text-xs text-bramble-muted tabular-nums shrink-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var16 string
		templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", lc.Count))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard_stats.templ`, Line: 179, Col: 110}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "</span></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// vlanCacheActivityCard shows vlancache's own outcome breakdown (hit /
// coalesced / miss) — a dimension independent of the Sources chart above,
// since a real miss that falls through to a forward is deliberately NOT
// attributed to Source "vlancache" (plugins/querylog's Entry.CacheOutcome
// doc comment explains why: Source is meant to answer "did this come from
// cache," and a miss didn't). This card instead answers "what has vlancache
// itself seen," including the misses the Sources chart intentionally
// excludes. Always shown once Query Log is on (see DashboardCharts' doc
// comment) — draws an empty chart until vlancache produces its first entry.
func vlanCacheActivityCard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var17 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var17 == nil {
			templ_7745c5c3_Var17 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "<div class=\"rounded border border-bramble-border bg-bramble-bg-card shadow-sm p-4 mb-4\"><h3 class=\"text-sm font-semibold mb-3 flex items-center\">Cache activity")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = helpTooltip("vlancache's own outcome breakdown: answered from cache, deduped against an in-flight identical request (coalesced), or a genuine miss that went to the network. Independent of the Sources chart, which only counts a query as \"vlancache\" when it actually came from the cache.").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "</h3><div class=\"h-48 relative\"><canvas id=\"chart-cache-activity\" data-chart=\"doughnut\"></canvas></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// clientActivityCard is pihole's "Client Activity" graph: query volume per
// client stacked over time, one series per top-N client plus a folded
// "Other" — mirrors topDomainsCard/topClientsCard's StoreConfigured gate
// since client-level granularity is Store-only (querylog.Log.ClientActivity).
func clientActivityCard(data DashboardActivityData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var18 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var18 == nil {
			templ_7745c5c3_Var18 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "<div class=\"rounded border border-bramble-border bg-bramble-bg-card shadow-sm p-4 mb-4\"><h3 class=\"text-sm font-semibold mb-3\">Client activity — last 24h</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !data.StoreConfigured {
			templ_7745c5c3_Err = statsStoreDisabledNote().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "<div class=\"h-48 relative\"><canvas id=\"chart-client-activity\" data-chart=\"stackedbar\"></canvas></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func topDomainsCard(data DashboardActivityData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var19 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var19 == nil {
			templ_7745c5c3_Var19 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "<div class=\"rounded border border-bramble-border bg-bramble-bg-card shadow-sm p-4\"><h3 class=\"text-sm font-semibold mb-3\">Top domains (24h)</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !data.StoreConfigured {
			templ_7745c5c3_Err = statsStoreDisabledNote().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if len(data.TopDomains) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "<p class=\"text-bramble-muted text-sm\">No queries yet.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "<table class=\"w-full text-sm\"><tbody>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, d := range data.TopDomains {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, "<tr class=\"border-b border-bramble-border last:border-0\"><td class=\"px-2 py-1.5 font-mono text-xs break-all\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var20 string
				templ_7745c5c3_Var20, templ_7745c5c3_Err = templ.JoinStringErrs(d.QName)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard_stats.templ`, Line: 233, Col: 68}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var20))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, "</td><td class=\"px-2 py-1.5 text-right text-xs tabular-nums text-bramble-muted\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var21 string
				templ_7745c5c3_Var21, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", d.Count))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard_stats.templ`, Line: 234, Col: 110}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var21))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, "</td></tr>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "</tbody></table>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func topClientsCard(data DashboardActivityData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var22 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var22 == nil {
			templ_7745c5c3_Var22 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "<div class=\"rounded border border-bramble-border bg-bramble-bg-card shadow-sm p-4\"><h3 class=\"text-sm font-semibold mb-3\">Top clients (24h)</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !data.StoreConfigured {
			templ_7745c5c3_Err = statsStoreDisabledNote().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if len(data.TopClients) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, "<p class=\"text-bramble-muted text-sm\">No queries yet.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, "<table class=\"w-full text-sm\"><tbody>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, c := range data.TopClients {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 39, "<tr class=\"border-b border-bramble-border last:border-0\"><td class=\"px-2 py-1.5\"><p class=\"font-mono text-xs\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var23 string
				templ_7745c5c3_Var23, templ_7745c5c3_Err = templ.JoinStringErrs(c.ClientIP)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard_stats.templ`, Line: 256, Col: 49}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var23))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 40, "</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if c.VLAN != "" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 41, "<p class=\"text-xs text-bramble-muted\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var24 string
					templ_7745c5c3_Var24, templ_7745c5c3_Err = templ.JoinStringErrs(c.VLAN)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard_stats.templ`, Line: 258, Col: 55}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var24))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 42, "</p>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 43, "</td><td class=\"px-2 py-1.5 text-right text-xs tabular-nums text-bramble-muted\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var25 string
				templ_7745c5c3_Var25, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", c.Count))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard_stats.templ`, Line: 261, Col: 110}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var25))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 44, "</td></tr>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 45, "</tbody></table>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 46, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func statsStoreDisabledNote() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var26 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var26 == nil {
			templ_7745c5c3_Var26 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 47, "<p class=\"text-bramble-muted text-sm\">Enable Query Log persistence in <a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var27 templ.SafeURL
		templ_7745c5c3_Var27, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(PathSettings))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard_stats.templ`, Line: 272, Col: 71}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var27))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 48, "\" class=\"text-bramble-primary hover:underline\">Settings</a> to see this.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// --- data shaping (plain Go, no chart config/color — that's charts.js's job) ---

// labelCount is a generic (label, count) pair, sorted descending by count
// for chart/list display — used for BySource/ByVLAN/ByQType alike.
type labelCount struct {
	Label string
	Count int64
}

func sortedCounts(m map[string]int64) []labelCount {
	out := make([]labelCount, 0, len(m))
	for k, v := range m {
		out = append(out, labelCount{Label: k, Count: v})
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Count != out[j].Count {
			return out[i].Count > out[j].Count
		}
		return out[i].Label < out[j].Label
	})
	return out
}

// foldOther caps a sorted-descending []labelCount at max entries, summing
// the remainder into a trailing "Other" — keeps doughnut charts within the
// categorical palette's well-validated slot count (dataviz skill: the
// default 8-hue order validates every *adjacent* pair, which includes the
// wraparound pair on a ring chart; capping at 6 stays comfortably inside
// that, and Pi-hole's own dashboard folds long tails the same way).
func foldOther(counts []labelCount, max int) []labelCount {
	if len(counts) <= max {
		return counts
	}
	out := append([]labelCount{}, counts[:max-1]...)
	var other int64
	for _, c := range counts[max-1:] {
		other += c.Count
	}
	return append(out, labelCount{Label: "Other", Count: other})
}

// nonEmptyCounts drops the "none" bucket ByCacheOutcome carries for queries
// that never reached the cache layer at all (querylog's handler.go defaults
// Entry.CacheOutcome to "none" rather than leaving it "") — irrelevant noise
// for a chart specifically about vlancache's own activity, unlike
// Sources/VLAN/QType charts where an empty Source/VLAN is itself a
// meaningful bucket (vlanBarLabel, sourceLabel).
func nonEmptyCounts(m map[string]int64) []labelCount {
	all := sortedCounts(m)
	out := make([]labelCount, 0, len(all))
	for _, c := range all {
		if c.Label != "none" {
			out = append(out, c)
		}
	}
	return out
}

// cacheOutcomeLabel maps Entry.CacheOutcome's raw values to display text for
// the "Cache activity" chart.
func cacheOutcomeLabel(outcome string) string {
	switch outcome {
	case "hit":
		return "Cache hit"
	case "coalesced":
		return "Coalesced"
	case "miss":
		return "Forwarded (miss)"
	default:
		return outcome
	}
}

// vlanBarLabel: an empty VLAN means "the client's address matched no
// configured VLAN" (querylog.ClientInfo's own doc comment) — shown as
// "(none)" rather than a blank bar label.
func vlanBarLabel(vlan string) string {
	if vlan == "" {
		return "(none)"
	}
	return vlan
}

// sourceGroupTotal sums BySource across the given Source values — the top
// tiles group by Source (which plugin actually handled the query), not
// Verdict (the outcome), so a tile's percentage always reflects real query
// volume: e.g. "Answered locally" counts everything localrecords/mdnsbridge/
// hosts took ownership of, including an authoritative NXDOMAIN denial for an
// owned zone, not just a successful answer (Verdict "local" alone
// undercounts this). Grouping this way keeps the four top tiles summing to
// Totals.Queries.
func sourceGroupTotal(bySource map[string]int64, sources ...string) int64 {
	var total int64
	for _, s := range sources {
		total += bySource[s]
	}
	return total
}

func pctLabel(part, total int64) string {
	if total == 0 {
		return "—"
	}
	return fmt.Sprintf("%.0f%%", 100*float64(part)/float64(total))
}

func barPct(count, total int64) float64 {
	if total == 0 {
		return 0
	}
	return 100 * float64(count) / float64(total)
}

// chartPayload is one chart's data in /api/dashboard/charts' JSON response —
// plain data only, no color/config (see static/js/charts.js's module doc
// comment for why that split exists: color/shape decisions live in JS,
// recomputed from this data on every poll).
type chartPayload struct {
	Labels []string `json:"labels"`
	Values []int64  `json:"values"`
}

// multiSeriesPayload is the stacked-bar chart's payload shape: shared bucket
// labels plus one named series per row (querylog.ClientActivityRow), each
// holding a value per bucket — unlike chartPayload, whose single Values
// slice pairs one value per label.
type multiSeriesPayload struct {
	Labels []string      `json:"labels"`
	Series []namedSeries `json:"series"`
}

type namedSeries struct {
	Name   string  `json:"name"`
	Values []int64 `json:"values"`
}

// DashboardChartsResponse is /api/dashboard/charts' JSON shape — one field
// per canvas in DashboardCharts, applied in place by charts.js's
// ChartManager on every poll (dev-docs/chartjs.md).
type DashboardChartsResponse struct {
	Series         chartPayload       `json:"series"`
	Sources        chartPayload       `json:"sources"`
	QTypes         chartPayload       `json:"qtypes"`
	CacheActivity  chartPayload       `json:"cacheActivity"`
	ClientActivity multiSeriesPayload `json:"clientActivity"`
}

// DashboardChartsPayload builds /api/dashboard/charts' response from the
// same DashboardActivityData the HTML shell (DashboardActivity) and initial
// chart render (DashboardCharts) use — one source of truth for chart data,
// reused by both the templ render path and this JSON path.
func DashboardChartsPayload(data DashboardActivityData) DashboardChartsResponse {
	return DashboardChartsResponse{
		Series:         seriesPayload(data.Series),
		Sources:        countsPayload(foldOther(sortedCounts(data.Totals.BySource), 6), sourceLabel),
		QTypes:         qtypeCountsPayload(data.Totals.ByQType),
		CacheActivity:  countsPayload(nonEmptyCounts(data.Totals.ByCacheOutcome), cacheOutcomeLabel),
		ClientActivity: clientActivityPayload(data.ClientActivity),
	}
}

func clientActivityPayload(ca querylog.ClientActivitySeries) multiSeriesPayload {
	p := multiSeriesPayload{Labels: make([]string, len(ca.Buckets)), Series: make([]namedSeries, len(ca.Rows))}
	for i, b := range ca.Buckets {
		p.Labels[i] = b.Format("15:04")
	}
	for i, row := range ca.Rows {
		p.Series[i] = namedSeries{Name: clientActivityRowLabel(row), Values: row.Counts}
	}
	return p
}

// clientActivityRowLabel mirrors vlanBarLabel's "(none)" convention for a
// client whose address matched no VLAN.
func clientActivityRowLabel(row querylog.ClientActivityRow) string {
	if row.IsOther {
		return "Other"
	}
	if row.VLAN == "" {
		return row.ClientIP
	}
	return fmt.Sprintf("%s (%s)", row.ClientIP, row.VLAN)
}

func seriesPayload(buckets []querylog.Bucket) chartPayload {
	p := chartPayload{Labels: make([]string, len(buckets)), Values: make([]int64, len(buckets))}
	for i, b := range buckets {
		p.Labels[i] = b.Start.Format("15:04")
		p.Values[i] = b.Count
	}
	return p
}

// countsPayload renders counts as a chartPayload, optionally relabeling
// each key (e.g. querylog's raw Source values -> sourceLabel's friendlier
// text) — labelFn nil means "use the label as-is" (QType is already
// relabeled to its RR type name before this is called, see
// qtypeCountsPayload). Starts from empty (not nil) slices: an empty counts
// (e.g. no vlancache activity yet, or a fresh install with zero queries)
// must still marshal as `"labels":[]`/`"values":[]`, not `null` — charts.js
// calls .map() on these unconditionally.
func countsPayload(counts []labelCount, labelFn func(string) string) chartPayload {
	p := chartPayload{Labels: []string{}, Values: []int64{}}
	for _, c := range counts {
		lbl := c.Label
		if labelFn != nil {
			lbl = labelFn(lbl)
		}
		p.Labels = append(p.Labels, lbl)
		p.Values = append(p.Values, c.Count)
	}
	return p
}

func qtypeCountsPayload(byQType map[uint16]int64) chartPayload {
	m := make(map[string]int64, len(byQType))
	for k, v := range byQType {
		name := dns.TypeToString[k]
		if name == "" {
			name = fmt.Sprintf("TYPE%d", k)
		}
		m[name] += v
	}
	return countsPayload(foldOther(sortedCounts(m), 6), nil)
}

var _ = templruntime.GeneratedTemplate
